# Statistics reported in the results part of the paper

In [93]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pingouin as pg

from suppression_oc.constants import (
TIMEPOINT_ORDER, TIMEPOINT_LABELS
)

from suppression_oc.util import ci95

plt.style.use("suppression_oc.notebook")

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [94]:
d_primes = pd.read_csv(
    "../data/signal_detection.csv"
)
d_primes_normal = d_primes[d_primes.condition == "normal"]

detection = pd.read_csv(
    "../data/tatai_et_al_detection.csv"
)

## Normal reaches ANOVA

In [95]:
anova_results = pg.rm_anova(
    data=d_primes_normal,
    dv="d_prime",
    within="timepoint_bin",
    subject="subject",
)
pg.print_table(anova_results)

=============
ANOVA SUMMARY
=============

Source           ddof1    ddof2       F    p-unc    p-GG-corr    ng2    eps  sphericity      W-spher    p-spher
-------------  -------  -------  ------  -------  -----------  -----  -----  ------------  ---------  ---------
timepoint_bin        7      210  34.255    0.000        0.000  0.328  0.413  False             0.011      0.000

#### Sphericity and Greenhouse-Geisser correction

In [96]:
from scipy.stats import f as f_dist


def gg_corrected_table(aov):
    """Greenhouse-Geisser corrected degrees of freedom and p values per effect."""
    return pd.DataFrame(
        [
            {
                "Source": effect["Source"],
                "F": effect["F"],
                "ddof1 (GG)": effect["ddof1"] * effect["eps"],
                "ddof2 (GG)": effect["ddof2"] * effect["eps"],
                "eps": effect["eps"],
                "p-unc": effect["p-unc"],
                "p-GG-corr": f_dist.sf(
                    effect["F"],
                    effect["ddof1"] * effect["eps"],
                    effect["ddof2"] * effect["eps"],
                ),
                "ng2": effect["ng2"],
            }
            for _, effect in aov.iterrows()
        ]
    )


print(
    anova_results[["Source", "W-spher", "p-spher", "sphericity"]].to_string(index=False)
)

gg_corrected_table(anova_results).round(3)

       Source  W-spher      p-spher  sphericity
timepoint_bin 0.011194 4.283304e-14       False

,Source,F,ddof1 (GG),ddof2 (GG),eps,p-unc,p-GG-corr,ng2
0,timepoint_bin,34.255,2.894,86.815,0.413,0.0,0.0,0.328

In [97]:
posthoc = pg.pairwise_tests(
    data=d_primes_normal,
    dv="d_prime",
    within="timepoint_bin",
    subject="subject",
    padjust="bonf",
    effsize="cohen",
)
pg.print_table(posthoc)

==============
POST HOC TESTS
==============

Contrast       A             B             Paired    Parametric          T     dof  alternative      p-unc    p-corr  p-adjust                BF10    cohen
-------------  ------------  ------------  --------  ------------  -------  ------  -------------  -------  --------  ----------  ----------------  -------
timepoint_bin  (-0.1, 0.0]   (-inf, -0.1]  True      True          -12.046  30.000  two-sided        0.000     0.000  bonf         15310000000.000   -1.715
timepoint_bin  (-0.1, 0.0]   (0.0, 0.2]    True      True            5.725  30.000  two-sided        0.000     0.000  bonf                6331.970    1.107
timepoint_bin  (-0.1, 0.0]   (0.2, 0.4]    True      True            3.236  30.000  two-sided        0.003     0.083  bonf                  12.702    0.636
timepoint_bin  (-0.1, 0.0]   (0.4, 0.6]    True      True            2.167  30.000  two-sided        0.038     1.000  bonf                   1.464    0.433
timepoint_bin  (-0.1, 0.0]   (0.6, 0.8]    True      True            0.030  30.000  two-sided        0.976     1.000  bonf                   0.192    0.006
timepoint_bin  (-0.1, 0.0]   (0.8, 1.0]    True      True           -2.308  30.000  two-sided        0.028     0.786  bonf                   1.883   -0.462
timepoint_bin  (-0.1, 0.0]   (1.0, inf]    True      True           -3.032  30.000  two-sided        0.005     0.139  bonf                   8.088   -0.543
timepoint_bin  (-inf, -0.1]  (0.0, 0.2]    True      True           13.345  30.000  two-sided        0.000     0.000  bonf        184100000000.000    3.125
timepoint_bin  (-inf, -0.1]  (0.2, 0.4]    True      True           10.408  30.000  two-sided        0.000     0.000  bonf           515200000.000    2.443
timepoint_bin  (-inf, -0.1]  (0.4, 0.6]    True      True            8.646  30.000  two-sided        0.000     0.000  bonf             9516000.000    2.013
timepoint_bin  (-inf, -0.1]  (0.6, 0.8]    True      True            6.241  30.000  two-sided        0.000     0.000  bonf               24070.000    1.463
timepoint_bin  (-inf, -0.1]  (0.8, 1.0]    True      True            4.168  30.000  two-sided        0.000     0.007  bonf                 117.102    0.917
timepoint_bin  (-inf, -0.1]  (1.0, inf]    True      True            3.973  30.000  two-sided        0.000     0.012  bonf                  72.272    0.779
timepoint_bin  (0.0, 0.2]    (0.2, 0.4]    True      True           -2.791  30.000  two-sided        0.009     0.254  bonf                   4.844   -0.427
timepoint_bin  (0.0, 0.2]    (0.4, 0.6]    True      True           -2.248  30.000  two-sided        0.032     0.897  bonf                   1.690   -0.498
timepoint_bin  (0.0, 0.2]    (0.6, 0.8]    True      True           -3.817  30.000  two-sided        0.001     0.018  bonf                  49.503   -0.889
timepoint_bin  (0.0, 0.2]    (0.8, 1.0]    True      True           -5.837  30.000  two-sided        0.000     0.000  bonf                8461.962   -1.347
timepoint_bin  (0.0, 0.2]    (1.0, inf]    True      True           -6.225  30.000  two-sided        0.000     0.000  bonf               23110.000   -1.391
timepoint_bin  (0.2, 0.4]    (0.4, 0.6]    True      True           -0.914  30.000  two-sided        0.368     1.000  bonf                   0.281   -0.130
timepoint_bin  (0.2, 0.4]    (0.6, 0.8]    True      True           -3.283  30.000  two-sided        0.003     0.073  bonf                  14.134   -0.527
timepoint_bin  (0.2, 0.4]    (0.8, 1.0]    True      True           -5.898  30.000  two-sided        0.000     0.000  bonf                9916.576   -0.980
timepoint_bin  (0.2, 0.4]    (1.0, inf]    True      True           -5.996  30.000  two-sided        0.000     0.000  bonf               12800.000   -1.041
timepoint_bin  (0.4, 0.6]    (0.6, 0.8]    True      True           -3.747  30.000  two-sided        0.001     0.021  bonf                  41.811   -0.370
timepoint_bin  (0.4, 0.6]    (0.8, 1.0]    True      True           -6.173  30.000  two-sided        0.000     0.000  bonf               20230.000   -0.796
timepoint_bin  (0.4, 0.6]    (1.0, inf]    True      True           -6.339  30.000  two-sided        0.000     0.000  bonf               30990.000   -0.862
timepoint_bin  (0.6, 0.8]    (0.8, 1.0]    True      True           -6.337  30.000  two-sided        0.000     0.000  bonf               30810.000   -0.418
timepoint_bin  (0.6, 0.8]    (1.0, inf]    True      True           -4.724  30.000  two-sided        0.000     0.001  bonf                 476.686   -0.495
timepoint_bin  (0.8, 1.0]    (1.0, inf]    True      True           -0.997  30.000  two-sided        0.327     1.000  bonf                   0.302   -0.087

## Comparison normal and initial uncertainty

In [98]:
kinematic_variables = {
    "reaction_time": "Mean reaction time [s]",
    "reach_time": "Mean movement time [s]",
    "max_v": "Mean max. velocity [m/s]",
    "t_max_v": "Mean time max. velocity [s]",
    "max_a": "Mean max. acceleration [m/s\u00b2]",
    "t_max_a": "Mean time max. acceleration [s]",
    "max_dec_a": "Mean max. deceleration [m/s\u00b2]",
    "t_max_dec_a": "Mean time max. deceleration [s]",
}

subject_means = detection.groupby(["condition", "subject"])[
    list(kinematic_variables)
].mean()


def mean_with_ci(values):
    """Mean across participants with its 95% confidence interval, as LaTeX."""
    half_width = ci95(len(values)) * values.sem()
    return (
        f"${values.mean():.3f}$ "
        f"$[{values.mean() - half_width:.3f}, {values.mean() + half_width:.3f}]$"
    )


summary_stats_formatted = pd.DataFrame(
    {
        condition: {
            label: mean_with_ci(subject_means.loc[condition, column])
            for column, label in kinematic_variables.items()
        }
        for condition in ["normal", "uncertain"]
    }
).rename(columns={"normal": r"\textit{certain}", "uncertain": r"\textit{uncertain}"})
summary_stats_formatted.index.name = "Kinematic variable"
summary_stats_formatted.columns.name = None

summary_stats_formatted

,\textit{certain},\textit{uncertain}
Kinematic variable,,
Mean reaction time [s],"$0.287$ $[0.274, 0.300]$","$0.284$ $[0.272, 0.296]$"
Mean movement time [s],"$0.671$ $[0.628, 0.714]$","$0.691$ $[0.648, 0.735]$"
Mean max. velocity [m/s],"$1.538$ $[1.421, 1.655]$","$1.490$ $[1.395, 1.585]$"
Mean time max. velocity [s],"$0.287$ $[0.263, 0.310]$","$0.298$ $[0.274, 0.322]$"
Mean max. acceleration [m/s²],"$19.902$ $[16.856, 22.949]$","$18.962$ $[16.026, 21.898]$"
Mean time max. acceleration [s],"$0.099$ $[0.083, 0.114]$","$0.105$ $[0.087, 0.122]$"
Mean max. deceleration [m/s²],"$9.201$ $[7.535, 10.868]$","$8.827$ $[7.276, 10.378]$"
Mean time max. deceleration [s],"$0.397$ $[0.369, 0.425]$","$0.414$ $[0.381, 0.446]$"

In [99]:
print(
    summary_stats_formatted.to_latex(
        escape=False,
        column_format="lll",
        caption=(
            r"Kinematic summary statistics for the \textit{certain} and "
            r"\textit{uncertain} conditions. Values are the mean across participants "
            r"($N=31$) of each participant's mean, with its 95\% confidence interval."
        ),
        label="tab:kinematics_summary",
    )
)

\begin{table}
\caption{Kinematic summary statistics for the \textit{certain} and \textit{uncertain} conditions. Values are the mean across participants ($N=31$) of each participant's mean, with its 95\% confidence interval.}
\label{tab:kinematics_summary}
\begin{tabular}{lll}
\toprule
 & \textit{certain} & \textit{uncertain} \\
Kinematic variable &  &  \\
\midrule
Mean reaction time [s] & $0.287$ $[0.274, 0.300]$ & $0.284$ $[0.272, 0.296]$ \\
Mean movement time [s] & $0.671$ $[0.628, 0.714]$ & $0.691$ $[0.648, 0.735]$ \\
Mean max. velocity [m/s] & $1.538$ $[1.421, 1.655]$ & $1.490$ $[1.395, 1.585]$ \\
Mean time max. velocity [s] & $0.287$ $[0.263, 0.310]$ & $0.298$ $[0.274, 0.322]$ \\
Mean max. acceleration [m/s²] & $19.902$ $[16.856, 22.949]$ & $18.962$ $[16.026, 21.898]$ \\
Mean time max. acceleration [s] & $0.099$ $[0.083, 0.114]$ & $0.105$ $[0.087, 0.122]$ \\
Mean max. deceleration [m/s²] & $9.201$ $[7.535, 10.868]$ & $8.827$ $[7.276, 10.378]$ \\
Mean time max. deceleration [s] & $0.397$ $[0.369, 0.425]$ & $0.414$ $[0.381, 0.446]$ \\
\bottomrule
\end{tabular}
\end{table}

### Reaction time

In [100]:
mean_reaction_times = detection.groupby(["condition", "subject"])[
    "reaction_time"
].mean()
mean_reaction_times = mean_reaction_times.reset_index(name="mean_reaction_time")
pg.ttest(
    mean_reaction_times.loc[
        mean_reaction_times.condition == "normal", "mean_reaction_time"
    ],
    mean_reaction_times.loc[
        mean_reaction_times.condition == "uncertain", "mean_reaction_time"
    ],
    paired=True,
)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,0.646034,30,two-sided,0.523169,"[-0.01, 0.01]",0.088828,0.232,0.076664

### Movement time

In [101]:
detection["reach_time"].describe()

count    13589.000000
mean         0.681528
std          0.137719
min          0.190617
25%          0.586915
50%          0.678857
75%          0.774406
max          1.784432
Name: reach_time, dtype: float64

In [102]:
mean_movement_times = detection.groupby(["condition", "subject"])["reach_time"].mean()
mean_movement_times = mean_movement_times.reset_index(name="mean_movement_time")
pg.ttest(
    mean_movement_times.loc[
        mean_movement_times.condition == "normal", "mean_movement_time"
    ],
    mean_movement_times.loc[
        mean_movement_times.condition == "uncertain", "mean_movement_time"
    ],
    paired=True,
    alternative="two-sided",
)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-2.361136,30,two-sided,0.024911,"[-0.04, -0.0]",0.172523,2.077,0.153455

In [103]:
print(
    "Mean diff:",
    np.mean(
        mean_movement_times.loc[
            mean_movement_times.condition == "normal", "mean_movement_time"
        ].values
        - mean_movement_times.loc[
            mean_movement_times.condition == "uncertain", "mean_movement_time"
        ].values
    ),
)

Mean diff: -0.02020270432391447

### Maximum velocity

In [104]:
mean_max_velocities = detection.groupby(["condition", "subject"])["max_v"].mean()
mean_max_velocities = mean_max_velocities.reset_index(name="mean_max_velocity")
pg.ttest(
    mean_max_velocities.loc[
        mean_max_velocities.condition == "normal", "mean_max_velocity"
    ],
    mean_max_velocities.loc[
        mean_max_velocities.condition == "uncertain", "mean_max_velocity"
    ],
    paired=True,
)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,1.381149,30,two-sided,0.177435,"[-0.02, 0.12]",0.166038,0.453,0.145623

### Time point of maximum velocity

In [105]:
mean_max_v_times = detection.groupby(["condition", "subject"])["t_max_v"].mean()
mean_max_v_times = mean_max_v_times.reset_index(name="mean_t_max_velocity")
pg.ttest(
    mean_max_v_times.loc[mean_max_v_times.condition == "normal", "mean_t_max_velocity"],
    mean_max_v_times.loc[
        mean_max_v_times.condition == "uncertain", "mean_t_max_velocity"
    ],
    paired=True,
)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-2.037884,30,two-sided,0.050464,"[-0.02, 0.0]",0.17102,1.173,0.151611

### Endpoint error

In [106]:
mean_vertical_errors = detection.groupby(["condition", "subject"])[
    "vertical_error"
].mean()
mean_vertical_errors = mean_vertical_errors.reset_index(name="mean_vertical_error")
pg.ttest(
    mean_vertical_errors.loc[
        mean_vertical_errors.condition == "normal", "mean_vertical_error"
    ],
    mean_vertical_errors.loc[
        mean_vertical_errors.condition == "uncertain", "mean_vertical_error"
    ],
    paired=True,
)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-0.976049,30,two-sided,0.336845,"[-0.0, 0.0]",0.095892,0.296,0.081142

### Detection ANOVA

In [107]:
anova_results = pg.rm_anova(
    data=d_primes,
    dv="d_prime",
    within=["timepoint_bin", "condition"],
    subject="subject",
)
pg.print_table(anova_results)

=============
ANOVA SUMMARY
=============

Source                          SS    ddof1    ddof2      MS       F    p-unc    p-GG-corr    ng2    eps
-------------------------  -------  -------  -------  ------  ------  -------  -----------  -----  -----
timepoint_bin              270.243        7      210  38.606  40.162    0.000        0.000  0.333  0.364
condition                   13.881        1       30  13.881   8.347    0.007        0.007  0.025  1.000
timepoint_bin * condition    0.670        7      210   0.096   0.553    0.794        0.732  0.001  0.698

#### Sphericity and Greenhouse-Geisser correction

In [108]:
d_primes_per_bin = d_primes.groupby(["subject", "timepoint_bin"], as_index=False)[
    "d_prime"
].mean()

sphericity_tests = {
    "timepoint_bin": pg.sphericity(
        d_primes_per_bin, dv="d_prime", subject="subject", within="timepoint_bin"
    ),
    "timepoint_bin * condition": pg.sphericity(
        d_primes, dv="d_prime", subject="subject", within=["condition", "timepoint_bin"]
    ),
}

for effect, result in sphericity_tests.items():
    print(
        f"{effect:26s} W = {result.W:.4f}, chi2({result.dof}) = {result.chi2:.2f}, "
        f"p = {result.pval:.3g}, sphericity = {result.spher}"
    )
print(f"{'condition':26s} only two levels, so sphericity holds by construction")

gg_corrected_table(anova_results).round(3)

timepoint_bin              W = 0.0040, chi2(27) = 151.32, p = 5.17e-19, sphericity = False
timepoint_bin * condition  W = 0.2455, chi2(27) = 38.55, p = 0.072, sphericity = True
condition                  only two levels, so sphericity holds by construction

,Source,F,ddof1 (GG),ddof2 (GG),eps,p-unc,p-GG-corr,ng2
0,timepoint_bin,40.162,2.550,76.510,0.364,0.000,0.000,0.333
1,condition,8.347,1.000,30.000,1.000,0.007,0.007,0.025
2,timepoint_bin * condition,0.553,4.889,146.682,0.698,0.794,0.732,0.001

In [109]:
posthoc = pg.pairwise_tests(
    data=d_primes,
    dv="d_prime",
    within=["timepoint_bin", "condition"],
    subject="subject",
    padjust="bonf",
    effsize="cohen"
)
# posthoc
pg.print_table(posthoc)

==============
POST HOC TESTS
==============

Contrast                   timepoint_bin    A             B             Paired    Parametric          T     dof  alternative      p-unc    p-corr  p-adjust                  BF10    cohen
-------------------------  ---------------  ------------  ------------  --------  ------------  -------  ------  -------------  -------  --------  ----------  ------------------  -------
timepoint_bin              -                (-0.1, 0.0]   (-inf, -0.1]  True      True          -13.777  30.000  two-sided        0.000     0.000  bonf          405900000000.000   -1.965
timepoint_bin              -                (-0.1, 0.0]   (0.0, 0.2]    True      True            6.554  30.000  two-sided        0.000     0.000  bonf                 53900.000    1.214
timepoint_bin              -                (-0.1, 0.0]   (0.2, 0.4]    True      True            3.852  30.000  two-sided        0.001     0.016  bonf                    53.819    0.827
timepoint_bin              -                (-0.1, 0.0]   (0.4, 0.6]    True      True            2.811  30.000  two-sided        0.009     0.242  bonf                     5.049    0.566
timepoint_bin              -                (-0.1, 0.0]   (0.6, 0.8]    True      True            0.183  30.000  two-sided        0.856     1.000  bonf                     0.195    0.041
timepoint_bin              -                (-0.1, 0.0]   (0.8, 1.0]    True      True           -2.128  30.000  two-sided        0.042     1.000  bonf                     1.368   -0.453
timepoint_bin              -                (-0.1, 0.0]   (1.0, inf]    True      True           -2.952  30.000  two-sided        0.006     0.170  bonf                     6.806   -0.567
timepoint_bin              -                (-inf, -0.1]  (0.0, 0.2]    True      True           15.770  30.000  two-sided        0.000     0.000  bonf        12480000000000.000    3.652
timepoint_bin              -                (-inf, -0.1]  (0.2, 0.4]    True      True           12.039  30.000  two-sided        0.000     0.000  bonf           15100000000.000    2.910
timepoint_bin              -                (-inf, -0.1]  (0.4, 0.6]    True      True            9.919  30.000  two-sided        0.000     0.000  bonf             176200000.000    2.432
timepoint_bin              -                (-inf, -0.1]  (0.6, 0.8]    True      True            6.319  30.000  two-sided        0.000     0.000  bonf                 29410.000    1.584
timepoint_bin              -                (-inf, -0.1]  (0.8, 1.0]    True      True            4.388  30.000  two-sided        0.000     0.004  bonf                   203.138    1.025
timepoint_bin              -                (-inf, -0.1]  (1.0, inf]    True      True            4.262  30.000  two-sided        0.000     0.005  bonf                   147.814    0.922
timepoint_bin              -                (0.0, 0.2]    (0.2, 0.4]    True      True           -1.998  30.000  two-sided        0.055     1.000  bonf                     1.097   -0.294
timepoint_bin              -                (0.0, 0.2]    (0.4, 0.6]    True      True           -2.535  30.000  two-sided        0.017     0.468  bonf                     2.894   -0.481
timepoint_bin              -                (0.0, 0.2]    (0.6, 0.8]    True      True           -3.853  30.000  two-sided        0.001     0.016  bonf                    53.969   -0.880
timepoint_bin              -                (0.0, 0.2]    (0.8, 1.0]    True      True           -6.280  30.000  two-sided        0.000     0.000  bonf                 26670.000   -1.388
timepoint_bin              -                (0.0, 0.2]    (1.0, inf]    True      True           -7.078  30.000  two-sided        0.000     0.000  bonf                204400.000   -1.522
timepoint_bin              -                (0.2, 0.4]    (0.4, 0.6]    True      True           -1.554  30.000  two-sided        0.131     1.000  bonf                     0.565   -0.197
timepoint_bin              -                (0.2, 0.4]    (0.6, 0.8]    True      True           -3.498  30.000  two-sided        0.001     0.042  bonf                    23.166   -0.618
timepoint_bin              -                (0.2, 0.4]    (0.8, 1.0]    True      True           -6.380  30.000  two-sided        0.000     0.000  bonf                 34490.000   -1.102
timepoint_bin              -                (0.2, 0.4]    (1.0, inf]    True      True           -6.801  30.000  two-sided        0.000     0.000  bonf                101100.000   -1.223
timepoint_bin              -                (0.4, 0.6]    (0.6, 0.8]    True      True           -4.080  30.000  two-sided        0.000     0.009  bonf                    94.074   -0.425
timepoint_bin              -                (0.4, 0.6]    (0.8, 1.0]    True      True           -7.296  30.000  two-sided        0.000     0.000  bonf                353300.000   -0.890
timepoint_bin              -                (0.4, 0.6]    (1.0, inf]    True      True           -7.856  30.000  two-sided        0.000     0.000  bonf               1416000.000   -1.002
timepoint_bin              -                (0.6, 0.8]    (0.8, 1.0]    True      True           -6.276  30.000  two-sided        0.000     0.000  bonf                 26380.000   -0.427
timepoint_bin              -                (0.6, 0.8]    (1.0, inf]    True      True           -4.653  30.000  two-sided        0.000     0.002  bonf                   398.018   -0.524
timepoint_bin              -                (0.8, 1.0]    (1.0, inf]    True      True           -1.231  30.000  two-sided        0.228     1.000  bonf                     0.381   -0.092
condition                  -                normal        uncertain     True      True           -2.889  30.000  two-sided        0.007   nan      nan                      5.955   -0.421
timepoint_bin * condition  (-0.1, 0.0]      normal        uncertain     True      True           -4.136  30.000  two-sided        0.000     0.002  bonf                   108.194   -0.491
timepoint_bin * condition  (-inf, -0.1]     normal        uncertain     True      True           -2.015  30.000  two-sided        0.053     0.424  bonf                     1.129   -0.327
timepoint_bin * condition  (0.0, 0.2]       normal        uncertain     True      True           -3.535  30.000  two-sided        0.001     0.011  bonf                    25.297   -0.656
timepoint_bin * condition  (0.2, 0.4]       normal        uncertain     True      True           -1.769  30.000  two-sided        0.087     0.696  bonf                     0.767   -0.263
timepoint_bin * condition  (0.4, 0.6]       normal        uncertain     True      True           -1.810  30.000  two-sided        0.080     0.642  bonf                     0.816   -0.300
timepoint_bin * condition  (0.6, 0.8]       normal        uncertain     True      True           -2.111  30.000  two-sided        0.043     0.346  bonf                     1.327   -0.280
timepoint_bin * condition  (0.8, 1.0]       normal        uncertain     True      True           -1.880  30.000  two-sided        0.070     0.559  bonf                     0.908   -0.237
timepoint_bin * condition  (1.0, inf]       normal        uncertain     True      True           -1.590  30.000  two-sided        0.122     0.979  bonf                     0.593   -0.224

### SI Posthoc comparison table

In [110]:
cond_posthoc = (
    posthoc[posthoc["Contrast"] == "timepoint_bin * condition"]
    .set_index("timepoint_bin")
    .loc[TIMEPOINT_ORDER]
)

# pingouin contrasts certain (A) against uncertain (B). The table reports the
# uncertain - certain direction used throughout the Results text, so t and
# Cohen's d are sign-flipped to match the sign of Delta d'.
delta_paired = {
    b: (
        d_primes[d_primes.timepoint_bin == b]
        .pivot_table(index="subject", columns="condition", values="d_prime")
        .pipe(lambda p: p["uncertain"] - p["normal"])
    )
    for b in TIMEPOINT_ORDER
}
delta_d_prime = {b: delta_paired[b].mean() for b in TIMEPOINT_ORDER}
delta_d_prime_ci = {
    b: (
        delta_paired[b].mean() - ci95(len(delta_paired[b])) * delta_paired[b].sem(),
        delta_paired[b].mean() + ci95(len(delta_paired[b])) * delta_paired[b].sem(),
    )
    for b in TIMEPOINT_ORDER
}


def _fmt_p(p):
    return "$<.001$" if p < 0.001 else f"${p:.3f}$"


posthoc_table = pd.DataFrame(
    {
        r"$\Delta d'$": [f"${delta_d_prime[b]:.3f}$" for b in TIMEPOINT_ORDER],
        r"$95\% CI_{\Delta d'}$": [
            f"$[{delta_d_prime_ci[b][0]:.3f}, {delta_d_prime_ci[b][1]:.3f}]$"
            for b in TIMEPOINT_ORDER
        ],
        r"$\textit{t}(30)$": [f"${-cond_posthoc.loc[b, 'T']:.3f}$" for b in TIMEPOINT_ORDER],
        r"$\textit{d}$": [f"${-cond_posthoc.loc[b, 'cohen']:.3f}$" for b in TIMEPOINT_ORDER],
        r"$p_\text{Bonf}$": [
            _fmt_p(cond_posthoc.loc[b, "p-corr"]) for b in TIMEPOINT_ORDER
        ],
        r"$BF_{10}$": [
            f"${float(cond_posthoc.loc[b, 'BF10']):.2f}$" for b in TIMEPOINT_ORDER
        ],
    },
    index=list(map(lambda x: f"${x}$", TIMEPOINT_LABELS)),
)
posthoc_table.index.name = "Stimulation time bin"

print(
    posthoc_table.to_latex(
        escape=False,
        column_format="lllllll",
        caption=(
            r"Per-bin paired comparisons of tactile sensitivity ($d'$) between the "
            r"\textit{certain} and \textit{uncertain} conditions "
            r"($\Delta d' = d'_\text{uncertain}-d'_\text{certain}$, $N=31$), with its "
            r"95\% confidence interval, Cohen's $d$, Bonferroni-corrected "
            r"$p$ values, and Bayes factors $BF_{10}$."
        ),
        label="tab:uncertainty_posthoc",
    )
)

\begin{table}
\caption{Per-bin paired comparisons of tactile sensitivity ($d'$) between the \textit{certain} and \textit{uncertain} conditions ($\Delta d' = d'_\text{uncertain}-d'_\text{certain}$, $N=31$), with its 95\% confidence interval, Cohen's $d$, Bonferroni-corrected $p$ values, and Bayes factors $BF_{10}$.}
\label{tab:uncertainty_posthoc}
\begin{tabular}{lllllll}
\toprule
 & $\Delta d'$ & $95\% CI_{\Delta d'}$ & $\textit{t}(30)$ & $\textit{d}$ & $p_\text{Bonf}$ & $BF_{10}$ \\
Stimulation time bin &  &  &  &  &  &  \\
\midrule
$[<-.1]s$ & $0.263$ & $[-0.004, 0.530]$ & $2.015$ & $0.327$ & $0.424$ & $1.13$ \\
$(-.1, .0]s$ & $0.433$ & $[0.219, 0.647]$ & $4.136$ & $0.491$ & $0.002$ & $108.19$ \\
$(.0, .2]$ & $0.455$ & $[0.192, 0.718]$ & $3.535$ & $0.656$ & $0.011$ & $25.30$ \\
$(.2, .4]$ & $0.229$ & $[-0.035, 0.493]$ & $1.769$ & $0.263$ & $0.696$ & $0.77$ \\
$(.4, .6]$ & $0.317$ & $[-0.041, 0.674]$ & $1.810$ & $0.300$ & $0.642$ & $0.82$ \\
$(.6, .8]$ & $0.363$ & $[0.012, 0.714]$ & $2.111$ & $0.280$ & $0.346$ & $1.33$ \\
$(.8, 1.0]$ & $0.316$ & $[-0.027, 0.660]$ & $1.880$ & $0.237$ & $0.559$ & $0.91$ \\
$[>1.0]$ & $0.300$ & $[-0.085, 0.686]$ & $1.590$ & $0.224$ & $0.979$ & $0.59$ \\
\bottomrule
\end{tabular}
\end{table}